# Generated by Django 2.1.1 on 2018-10-07 17:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.IntegerField(unique=True)),
                ('Target_phone', models.IntegerField(unique=True)),
                ('Type', models.CharField(choices=[('Sn', 'Single'), ('Biz', 'Business'), ('Fm', 'Family')], max_length=12)),
                ('Status', models.CharField(choices=[('Sn', 'Single'), ('Ac', 'Active'), ('En', 'Engaged'), ('mr', 'Married')], max_length=12)),
                ('Goal', models.CharField(choices=[('Ac', 'Active'), ('Fr', 'Fairytale'), ('Pl', 'player')], max_length=12)),
                ('setup', models.BooleanField()),
                ('User', models.ForeignKey(on_delete='cascade', related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
