# Generated by Django 2.1.1 on 2018-10-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_nick_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='caller',
        ),
    ]
