# Generated by Django 2.1.1 on 2018-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='setup',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Setup',
            field=models.BooleanField(default=False),
        ),
    ]
