# Generated by Django 2.1.1 on 2018-10-22 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181012_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Goal',
            field=models.CharField(blank=True, choices=[('Ac', 'Active'), ('Fr', 'Fairytale'), ('Pl', 'player')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 11', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Status',
            field=models.CharField(blank=True, choices=[('Sn', 'Single'), ('Ac', 'Active'), ('En', 'Engaged'), ('mr', 'Married')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Target_phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 11', regex='^\\d{11}$')]),
        ),
    ]
