# Generated by Django 2.1.1 on 2018-10-22 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181022_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Status',
            field=models.CharField(choices=[('Sn', 'Single'), ('Ac', 'Active'), ('En', 'Engaged'), ('mr', 'Married')], max_length=12, verbose_name='Relationship status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Target_phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='invalid number', regex='^\\d{11}$')], verbose_name='spouse number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Type',
            field=models.CharField(choices=[('Sn', 'Single'), ('Fm', 'Family')], max_length=12),
        ),
    ]
