# Generated by Django 2.1.1 on 2018-10-22 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181022_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='invalid number', regex='^\\d{11}$')]),
        ),
    ]
