# Generated by Django 2.1.1 on 2018-10-18 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luvbytes', '0003_auto_20181018_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='owner',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
