# Generated by Django 2.1.1 on 2018-10-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luvbytes', '0002_sms_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='type',
            new_name='genre',
        ),
    ]
