# Generated by Django 2.1.1 on 2018-10-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luvbytes', '0006_remove_sms_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'sms'},
        ),
    ]
