# Generated by Django 2.1.1 on 2018-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luvbytes', '0007_auto_20181020_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='simple_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
